name: Deploy Tagged Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test-ssh:
    name: Test SSH Access
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH access verified: $(hostname)"

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test-ssh
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Set version from tag
      run: echo "GIT_TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Validate tag format
      run: |
        if [[ ! "${GIT_TAG_VERSION}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
          echo "::error::Invalid tag format: ${GIT_TAG_VERSION}. Expected format: v1.2.3 or v1.2.3-suffix"
          exit 1
        else
          echo "Valid tag format: ${GIT_TAG_VERSION}"
        fi

    - name: Build
      run: dotnet publish -c Release -o ./publish
      env:
        GIT_TAG_VERSION: ${{ env.GIT_TAG_VERSION }}

    - name: Create backup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          BACKUP_DIR="/srv/DiscordBots/Backups/AGCUtilsV2-${{ env.GIT_TAG_VERSION }}-$(date +%Y%m%d-%H%M%S)"
          mkdir -p $BACKUP_DIR
          # Copy everything except logs and data folders
          rsync -av --exclude='logs' --exclude='data' /srv/DiscordBots/AGCUtilsV2/ $BACKUP_DIR/ || echo "No files to backup or backup failed"
          ls -dt /srv/DiscordBots/Backups/AGCUtilsV2-* | tail -n +11 | xargs -r rm -rf
        timeout: 60s

    - name: Deploy to server
      id: deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./publish/*"
        target: "/srv/DiscordBots/AGCUtilsV2"
        strip_components: 1
        timeout: 120s

    - name: Restart service and verify
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart agc-utilsv2

          # Wait for service to start
          sleep 20

          if sudo systemctl is-active --quiet agc-utilsv2; then
            echo "Service started successfully"
            echo "Deployed version: ${{ env.GIT_TAG_VERSION }}"
          else
            echo "Service failed to start, rolling back to backup"
            LATEST_BACKUP=$(ls -dt /srv/DiscordBots/Backups/AGCUtilsV2-* | head -n 1)
            if [ -n "$LATEST_BACKUP" ]; then
              # Restore everything except logs and data folders
              rsync -av --exclude='logs' --exclude='data' $LATEST_BACKUP/ /srv/DiscordBots/AGCUtilsV2/
              sudo systemctl restart agc-utilsv2
              echo "Rolled back to $LATEST_BACKUP"
              exit 1
            else
              echo "No backup found, cannot roll back"
              exit 1
            fi
          fi
        timeout: 300s
